### ISSUE TITLE
Validación de campos vacíos mediante Bootstrap

### ISSUE THREAD

**Issue by virginiamercado** [PPROF1-2021/g2-a3-g2#14]
Validación de campos vacíos mediante Bootstrap (de acuerdo al template de la web oficial), luego con Javascript la longitud de los campos, tipo de datos en los input. Los campos nombre y apellido deberán validarse con más de 2 caracteres.

**Comment by gustavomiarka** [comment]
se agregó validación de campos vacios en form-registro y form-mascota.
